### ISSUE TITLE
Handle Landlock ABI 3 (truncate)

### ISSUE THREAD

**Issue by l0kod** [landlock-lsm/rust-landlock#28]
I have a set of commits to support the third ABI but they depend on compatibility fixes provided by #12.

**Comment by gnoack** [comment]
Go variant of this: https://github.com/landlock-lsm/go-landlock/commit/68354b78709b9f3d674b4435726c5530d42ffdc6, for reference

**Comment by l0kod** [comment]
Implemented with #40
