### ISSUE TITLE
Multiple `as_mut` implementations prevent automatic type resolution

### ISSUE THREAD

**Issue by cd-work** [landlock-lsm/rust-landlock#48]
Currently `RulesetCreated` has the following two `as_mut` implementations:

```
AsMut<Option<CompatLevel>> for RulesetCreated

impl AsMut<RulesetCreated> for RulesetCreated
```

I believe the `CompatLevel` one is new, which causes this previously working code to fail now:

```
landlock.as_mut().add_rule(rule)?;
```

This can be easily changed by changing it to `(&mut landlock)`, but I believe the purpose of this `as_mut` call was to make non-builder usecase like this easier and with the latest Landlock git version that purpose isn't really working out anymore.

This can be easily fixed by changing one or both of these impls to use a non-trait method instead (could even leave the trait impl too if that's necessary). It's not a massive deal but I was just curious if this regression is something you were aware of.

**Comment by l0kod** [comment]
Oh, I wasn't aware of this change. Could you please create a PR to fix it?

**Comment by l0kod** [comment]
I'd like to add this fix (with tests) before releasing a new version.
